name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    # TODO: eventually, this should just install the published version of this and use that
    - run: npm ci
    - run: node . ./node.pipeline.js
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ci-output
        path: ci-output/
