name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GH_NPM_TOKEN: '${{ secrets.GH_NPM_TOKEN }}'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: echo "//npm.pkg.github.com/:_authToken=$GH_NPM_TOKEN" > ~/.npmrc
    - run: echo "@dpgraham:registry=https://npm.pkg.github.com" >> ~/.npmrc
    - run: npm install
    - run: node . ./node.pipeline.js
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: output-ci
        path: output-ci/
