name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GH_NPM_TOKEN: '${{ secrets.GH_NPM_TOKEN }}'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: npm install
    - run: node . ./test-pipelines/tiny.pipeline.js
      name: Run Carry-On from source
    - run: npx carry-on ./node.pipeline.js
      name: Run MR verification pipeline via Carry-On
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: output-ci
        path: output-ci/
