name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    # TODO: Add a job that publishes package
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: npm install @dpgraham/carry-on@0.0.1
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: output-ci
        path: output-ci/
